name: Windows 10

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999

    steps:
    - name: Download Ngrok Baru
      run: |
        Invoke-WebRequest -Uri "https://downloads.ngrok.com/windows/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip

    - name: Extract Ngrok
      run: |
        Expand-Archive ngrok.zip -DestinationPath .
        Rename-Item -Path ".\ngrok-v3-stable-windows-amd64" -NewName "ngrok"

    - name: Auth
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Set Runner Password
      run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@WirpOnTop" -Force)

    - name: Run Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
