name: Windows 10

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 99999

    steps:
    - name: Download Ngrok Baru
      run: Invoke-WebRequest "https://downloads.ngrok.com/windows/ngrok-v3-stable-windows-amd64.zip" -OutFile ngrok.zip

    - name: Extract Ngrok (7zip Anti Error)
      run: |
        7z x ngrok.zip -ongrok_folder
        Rename-Item "ngrok_folder\ngrok-v3-stable-windows-amd64" "ngrok"

    - name: Auth
      run: .\ngrok\ngrok.exe config add-authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0

    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "@WirpOnTop" -Force)

    - name: Run Tunnel
      run: .\ngrok\ngrok.exe tcp 3389
